site_name: NH Switch Guide
nav:
    - Home: index.md
    - User Guide:
        - 'Getting Started': 'user_guide/getting_started.md'
        - 'SD Preparation': 'user_guide/sd_preparation.md'        
        - 'Entering RCM': 'user_guide/entering_rcm.md'
        - 'Sending a Payload': 'user_guide/sending_payload.md'
        - 'Making a NAND Backup': 'user_guide/making_a_nand_backup.md'
        - 'Launching CFW': 'user_guide/launching_cfw.md'
    - Advanced:
        - 'Theming': 'advanced/theming.md'
        - 'Game Modding': 'advanced/game_modding.md'        
        - 'Save Management': 'advanced/save_management.md'
        - 'Blocking Updates': 'advanced/blocking_updates.md'
    - Frequently Asked Questions: faq.md
    - About: about.md
    
markdown_extensions:
    - admonition
